# Predictive Modelling of Health Workforce Shortages Using Socio-Economic Determinants

## Data Understanding

In [2]:
# ==========================================
# ###  Import Libraries
# ==========================================

import pandas as pd
import numpy as np

print("Environment Ready")

Environment Ready

In [3]:
# ==========================================
# ###  Load Datasets
# ==========================================

df_gdp = pd.read_csv("../data/GDP.csv", skiprows=4)
df_health = pd.read_csv("../data/health_expenditure.csv", skiprows=4)
df_physicians = pd.read_csv("../data/physicians.csv", skiprows=4)
df_population = pd.read_csv("../data/population_growth.csv", skiprows=4)
df_school = pd.read_csv("../data/school_enrollment.csv", skiprows=4)
df_unemployment = pd.read_csv("../data/unemployment.csv", skiprows=4)
df_urban = pd.read_csv("../data/urban_population.csv", skiprows=4)

print("Datasets Loaded Successfully")

Datasets Loaded Successfully

In [4]:
datasets = {
    "physicians": df_physicians,
    "gdp": df_gdp,
    "health_expenditure": df_health,
    "population_growth": df_population,
    "school_enrollment": df_school,
    "unemployment": df_unemployment,
    "urban_population": df_urban
}

for name, df in datasets.items():
    print(f"\n===== {name.upper()} =====")
    print("Shape:", df.shape)
    print(df.info())


for name, df in datasets.items():
    print(f"\n===== {name.upper()} HEAD =====")
    display(df.head())


for name, df in datasets.items():
    print(f"\n===== {name.upper()} Missing Values =====")
    print(df.isnull().sum().sort_values(ascending=False).head())

===== PHYSICIANS =====
Shape: (266, 70)
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            137 non-null    float64
 5   1961            18 non-null     float64
 6   1962            16 non-null     float64
 7   1963            16 non-null     float64
 8   1964            16 non-null     float64
 9   1965            108 non-null    float64
 10  1966            19 non-null     float64
 11  1967            17 non-null     float64
 12  1968            17 non-null     float64
 13  1969            17 non-null     float64
 14  1970            146 non-null    float64
 15  1971            28 non-null     float64
 16  1972            24 non-null     float64
 17  1973            26 non-null     float64
 18  1974            23 non-null     float64
 19  1975            85 non-null     float64
 20  1976            28 non-null     float64
 21  1977            29 non-null     float64
 22  1978            27 non-null     float64
 23  1979            37 non-null     float64
 24  1980            83 non-null     float64
 25  1981            99 non-null     float64
 26  1982            48 non-null     float64
 27  1983            42 non-null     float64
 28  1984            79 non-null     float64
 29  1985            72 non-null     float64
 30  1986            66 non-null     float64
 31  1987            51 non-null     float64
 32  1988            53 non-null     float64
 33  1989            56 non-null     float64
 34  1990            185 non-null    float64
 35  1991            91 non-null     float64
 36  1992            88 non-null     float64
 37  1993            111 non-null    float64
 38  1994            83 non-null     float64
 39  1995            124 non-null    float64
 40  1996            99 non-null     float64
 41  1997            108 non-null    float64
 42  1998            89 non-null     float64
 43  1999            87 non-null     float64
 44  2000            143 non-null    float64
 45  2001            101 non-null    float64
 46  2002            95 non-null     float64
 47  2003            96 non-null     float64
 48  2004            140 non-null    float64
 49  2005            108 non-null    float64
 50  2006            103 non-null    float64
 51  2007            112 non-null    float64
 52  2008            134 non-null    float64
 53  2009            131 non-null    float64
 54  2010            171 non-null    float64
 55  2011            116 non-null    float64
 56  2012            119 non-null    float64
 57  2013            117 non-null    float64
 58  2014            124 non-null    float64
 59  2015            122 non-null    float64
 60  2016            131 non-null    float64
 61  2017            139 non-null    float64
 62  2018            157 non-null    float64
 63  2019            135 non-null    float64
 64  2020            136 non-null    float64
 65  2021            123 non-null    float64
 66  2022            172 non-null    float64
 67  2023            58 non-null     float64
 68  2024            0 non-null      float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB
None

===== GDP =====
Shape: (266, 70)
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            151 non-null    float64
 5   1961            154 non-null    float64
 6   1962            156 non-null    float64
 7   1963            156 non-null    float64
 8   1964            156 non-null    float64
 9   1965            162 non-null    float64
 10  1966            163 non-null    float64
 11  1967            167 non-null    float64
 12  1968            168 non-null    float64
 13  1969            168 non-null    float64
 14  1970            190 non-null    float64
 15  1971            191 non-null    float64
 16  1972            191 non-null    float64
 17  1973            191 non-null    float64
 18  1974            191 non-null    float64
 19  1975            195 non-null    float64
 20  1976            195 non-null    float64
 21  1977            198 non-null    float64
 22  1978            197 non-null    float64
 23  1979            198 non-null    float64
 24  1980            208 non-null    float64
 25  1981            208 non-null    float64
 26  1982            209 non-null    float64
 27  1983            209 non-null    float64
 28  1984            211 non-null    float64
 29  1985            213 non-null    float64
 30  1986            213 non-null    float64
 31  1987            220 non-null    float64
 32  1988            223 non-null    float64
 33  1989            223 non-null    float64
 34  1990            240 non-null    float64
 35  1991            241 non-null    float64
 36  1992            242 non-null    float64
 37  1993            243 non-null    float64
 38  1994            244 non-null    float64
 39  1995            247 non-null    float64
 40  1996            247 non-null    float64
 41  1997            249 non-null    float64
 42  1998            250 non-null    float64
 43  1999            250 non-null    float64
 44  2000            252 non-null    float64
 45  2001            253 non-null    float64
 46  2002            257 non-null    float64
 47  2003            257 non-null    float64
 48  2004            257 non-null    float64
 49  2005            257 non-null    float64
 50  2006            258 non-null    float64
 51  2007            258 non-null    float64
 52  2008            259 non-null    float64
 53  2009            261 non-null    float64
 54  2010            261 non-null    float64
 55  2011            262 non-null    float64
 56  2012            260 non-null    float64
 57  2013            260 non-null    float64
 58  2014            261 non-null    float64
 59  2015            260 non-null    float64
 60  2016            259 non-null    float64
 61  2017            259 non-null    float64
 62  2018            259 non-null    float64
 63  2019            259 non-null    float64
 64  2020            258 non-null    float64
 65  2021            258 non-null    float64
 66  2022            257 non-null    float64
 67  2023            251 non-null    float64
 68  2024            240 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB
None

===== HEALTH_EXPENDITURE =====
Shape: (266, 70)
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            0 non-null      float64
 35  1991            0 non-null      float64
 36  1992            0 non-null      float64
 37  1993            0 non-null      float64
 38  1994            0 non-null      float64
 39  1995            0 non-null      float64
 40  1996            0 non-null      float64
 41  1997            0 non-null      float64
 42  1998            0 non-null      float64
 43  1999            0 non-null      float64
 44  2000            232 non-null    float64
 45  2001            232 non-null    float64
 46  2002            233 non-null    float64
 47  2003            235 non-null    float64
 48  2004            235 non-null    float64
 49  2005            235 non-null    float64
 50  2006            235 non-null    float64
 51  2007            235 non-null    float64
 52  2008            235 non-null    float64
 53  2009            235 non-null    float64
 54  2010            236 non-null    float64
 55  2011            237 non-null    float64
 56  2012            237 non-null    float64
 57  2013            239 non-null    float64
 58  2014            239 non-null    float64
 59  2015            239 non-null    float64
 60  2016            239 non-null    float64
 61  2017            240 non-null    float64
 62  2018            241 non-null    float64
 63  2019            241 non-null    float64
 64  2020            241 non-null    float64
 65  2021            241 non-null    float64
 66  2022            240 non-null    float64
 67  2023            240 non-null    float64
 68  2024            24 non-null     float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB
None

===== POPULATION_GROWTH =====
Shape: (266, 70)
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            0 non-null      float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            264 non-null    float64
 35  1991            264 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            264 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB
None

===== SCHOOL_ENROLLMENT =====
Shape: (266, 70)
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            54 non-null     float64
 15  1971            96 non-null     float64
 16  1972            89 non-null     float64
 17  1973            91 non-null     float64
 18  1974            90 non-null     float64
 19  1975            91 non-null     float64
 20  1976            90 non-null     float64
 21  1977            93 non-null     float64
 22  1978            91 non-null     float64
 23  1979            97 non-null     float64
 24  1980            96 non-null     float64
 25  1981            104 non-null    float64
 26  1982            98 non-null     float64
 27  1983            94 non-null     float64
 28  1984            99 non-null     float64
 29  1985            98 non-null     float64
 30  1986            103 non-null    float64
 31  1987            97 non-null     float64
 32  1988            90 non-null     float64
 33  1989            96 non-null     float64
 34  1990            95 non-null     float64
 35  1991            94 non-null     float64
 36  1992            94 non-null     float64
 37  1993            86 non-null     float64
 38  1994            80 non-null     float64
 39  1995            85 non-null     float64
 40  1996            80 non-null     float64
 41  1997            65 non-null     float64
 42  1998            68 non-null     float64
 43  1999            122 non-null    float64
 44  2000            154 non-null    float64
 45  2001            160 non-null    float64
 46  2002            172 non-null    float64
 47  2003            172 non-null    float64
 48  2004            171 non-null    float64
 49  2005            168 non-null    float64
 50  2006            168 non-null    float64
 51  2007            165 non-null    float64
 52  2008            172 non-null    float64
 53  2009            176 non-null    float64
 54  2010            181 non-null    float64
 55  2011            184 non-null    float64
 56  2012            188 non-null    float64
 57  2013            177 non-null    float64
 58  2014            183 non-null    float64
 59  2015            193 non-null    float64
 60  2016            181 non-null    float64
 61  2017            181 non-null    float64
 62  2018            178 non-null    float64
 63  2019            176 non-null    float64
 64  2020            176 non-null    float64
 65  2021            168 non-null    float64
 66  2022            161 non-null    float64
 67  2023            161 non-null    float64
 68  2024            95 non-null     float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB
None

===== UNEMPLOYMENT =====
Shape: (266, 70)
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            0 non-null      float64
 35  1991            235 non-null    float64
 36  1992            235 non-null    float64
 37  1993            235 non-null    float64
 38  1994            235 non-null    float64
 39  1995            235 non-null    float64
 40  1996            235 non-null    float64
 41  1997            235 non-null    float64
 42  1998            235 non-null    float64
 43  1999            235 non-null    float64
 44  2000            235 non-null    float64
 45  2001            235 non-null    float64
 46  2002            235 non-null    float64
 47  2003            235 non-null    float64
 48  2004            235 non-null    float64
 49  2005            235 non-null    float64
 50  2006            235 non-null    float64
 51  2007            235 non-null    float64
 52  2008            235 non-null    float64
 53  2009            235 non-null    float64
 54  2010            235 non-null    float64
 55  2011            235 non-null    float64
 56  2012            235 non-null    float64
 57  2013            235 non-null    float64
 58  2014            235 non-null    float64
 59  2015            235 non-null    float64

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Physicians (per 1,000 people)",SH.MED.PHYS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Physicians (per 1,000 people)",SH.MED.PHYS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.243385,NaN,NaN,NaN
2,Afghanistan,AFG,"Physicians (per 1,000 people)",SH.MED.PHYS.ZS,0.035,NaN,NaN,NaN,NaN,0.063,...,0.284,0.245,0.303,0.214,0.253,NaN,NaN,0.317,NaN,NaN
3,Africa Western and Central,AFW,"Physicians (per 1,000 people)",SH.MED.PHYS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.258636,NaN,NaN,NaN
4,Angola,AGO,"Physicians (per 1,000 people)",SH.MED.PHYS.ZS,0.067,NaN,NaN,NaN,NaN,0.076,...,NaN,0.212,0.211,NaN,NaN,NaN,0.244000,NaN,NaN,NaN

===== GDP HEAD =====

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.983637e+09,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,8.318681e+11,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,...,7.000282e+11,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11,NaN

===== HEALTH_EXPENDITURE HEAD =====

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.014036,5.865882,5.730629,5.755890,5.984597,5.942595,5.559021,5.540810,NaN,NaN
2,Afghanistan,AFG,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.818590,12.620817,14.208419,14.831320,15.533614,21.508444,23.088169,14.985763,NaN,NaN
3,Africa Western and Central,AFW,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.802756,3.732668,3.288622,3.250936,3.788444,4.135622,4.174496,4.143225,NaN,NaN
4,Angola,AGO,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.390687,2.437943,2.298875,2.203943,2.816889,2.739871,2.600410,2.546929,NaN,NaN

===== POPULATION_GROWTH HEAD =====

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,Population growth (annual %),SP.POP.GROW,NaN,1.187344,1.326227,1.203664,1.076602,0.986114,...,0.757968,0.007358,0.158976,0.270505,-0.565684,-0.820211,-0.362774,0.045652,0.590657,NaN
1,Africa Eastern and Southern,AFE,Population growth (annual %),SP.POP.GROW,NaN,2.624624,2.687009,2.714042,2.769856,2.809882,...,2.640743,2.642067,2.734263,2.721681,2.699516,2.649439,2.592754,2.519167,2.472801,NaN
2,Afghanistan,AFG,Population growth (annual %),SP.POP.GROW,NaN,1.962239,2.044523,2.105208,2.161195,2.233709,...,2.535720,2.808337,2.910810,2.984389,3.153609,2.356098,1.435704,2.135594,2.836573,NaN
3,Africa Western and Central,AFW,Population growth (annual %),SP.POP.GROW,NaN,2.103832,2.131522,2.170015,2.184894,2.216283,...,2.672913,2.626296,2.533621,2.440048,2.389176,2.363829,2.332270,2.386204,2.398473,NaN
4,Angola,AGO,Population growth (annual %),SP.POP.GROW,NaN,1.327797,0.989639,1.003666,1.027684,1.052133,...,3.576441,3.540612,3.453233,3.387884,3.267959,3.181323,3.143026,3.080655,3.044200,NaN

===== SCHOOL_ENROLLMENT HEAD =====

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"School enrollment, tertiary (% gross)",SE.TER.ENRR,NaN,NaN,NaN,NaN,NaN,NaN,...,17.141621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.065542,NaN
1,Africa Eastern and Southern,AFE,"School enrollment, tertiary (% gross)",SE.TER.ENRR,NaN,NaN,NaN,NaN,NaN,NaN,...,8.573140,8.71269,8.75093,8.67273,8.71187,8.66186,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,"School enrollment, tertiary (% gross)",SE.TER.ENRR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.99592,NaN,10.85436,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,"School enrollment, tertiary (% gross)",SE.TER.ENRR,NaN,NaN,NaN,NaN,NaN,NaN,...,9.269370,9.39776,9.58899,9.73876,9.93538,10.19026,NaN,NaN,NaN,NaN
4,Angola,AGO,"School enrollment, tertiary (% gross)",SE.TER.ENRR,NaN,NaN,NaN,NaN,NaN,NaN,...,9.782877,NaN,NaN,NaN,NaN,NaN,NaN,10.049358,9.954907,NaN

===== UNEMPLOYMENT HEAD =====

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.074429,7.214915,7.244843,7.459106,7.974302,8.407412,7.869470,7.676548,7.571697,NaN
2,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.116000,11.184000,11.192000,11.187000,11.710000,12.006000,14.100000,14.008000,13.687000,NaN
3,Africa Western and Central,AFW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.167580,4.283996,4.334377,4.390764,4.795318,4.666634,3.593354,3.200801,3.172421,NaN
4,Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.572000,16.617000,16.602000,16.497000,16.696000,15.799000,14.124000,14.051000,14.020000,NaN

===== URBAN_POPULATION HEAD =====

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,59.023670,59.072800,59.212271,59.432359,59.723340,60.075491,...,63.007788,62.776849,62.536764,62.288276,62.002884,61.927534,61.881166,61.835149,61.790940,NaN
1,Africa Eastern and Southern,AFE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,14.640371,14.867730,15.107367,15.353899,15.607152,15.872246,...,34.881211,35.282987,35.714718,36.097331,36.488322,36.908543,37.360578,37.772301,38.241441,NaN
2,Afghanistan,AFG,Urban population (% of total population),SP.URB.TOTL.IN.ZS,8.122551,8.389595,8.662664,8.942709,9.231134,9.529343,...,24.658835,24.835282,24.999165,25.143726,25.262210,25.347862,25.393925,25.473053,25.700735,NaN
3,Africa Western and Central,AFW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,13.946480,14.468419,15.017383,15.592318,16.190580,16.814002,...,48.173970,48.747414,49.317948,49.890075,50.476318,51.072397,51.681694,52.282908,52.859564,NaN
4,Angola,AGO,Urban population (% of total population),SP.URB.TOTL.IN.ZS,10.387104,10.810545,11.207060,11.581720,11.945180,12.308095,...,64.299230,65.085053,65.873214,66.663782,67.456827,68.252416,69.050619,69.851503,70.655138,NaN

===== PHYSICIANS Missing Values =====
2024           266
Unnamed: 69    266
1963           250
1962           250
1964           250
dtype: int64

===== GDP Missing Values =====
Unnamed: 69    266
1960           115
1961           112
1963           110
1962           110
dtype: int64

===== HEALTH_EXPENDITURE Missing Values =====
1960    266
1961    266
1965    266
1964    266
1963    266
dtype: int64

===== POPULATION_GROWTH Missing Values =====
1960           266
Unnamed: 69    266
1963             2
1964             2
1962             2
dtype: int64

===== SCHOOL_ENROLLMENT Missing Values =====
1960    266
1961    266
1965    266
1964    266
1963    266
dtype: int64

===== UNEMPLOYMENT Missing Values =====
1960    266
1961    266
1965    266
1964    266
1963    266
dtype: int64

===== URBAN_POPULATION Missing Values =====
Unnamed: 69    266
1960             1
1963             1
1964             1
1962             1
dtype: int64

In [5]:
df_physicians["Country Name"].nunique()
df_physicians["Country Name"].unique()[:20]

<StringArray>
[                      'Aruba', 'Africa Eastern and Southern',
                 'Afghanistan',  'Africa Western and Central',
                      'Angola',                     'Albania',
                     'Andorra',                  'Arab World',
        'United Arab Emirates',                   'Argentina',
                     'Armenia',              'American Samoa',
         'Antigua and Barbuda',                   'Australia',
                     'Austria',                  'Azerbaijan',
                     'Burundi',                     'Belgium',
                       'Benin',                'Burkina Faso']
Length: 20, dtype: str

In [6]:
regions = df_physicians[
    df_physicians["Country Name"].str.contains("Africa|World|Europe|Asia|OECD|income", case=False, na=False)
]

regions["Country Name"].unique()

<StringArray>
[                                              'Africa Eastern and Southern',
                                                'Africa Western and Central',
                                                                'Arab World',
                                                  'Central African Republic',
                                            'Central Europe and the Baltics',
                               'East Asia & Pacific (excluding high income)',
                                                       'East Asia & Pacific',
                             'Europe & Central Asia (excluding high income)',
                                                     'Europe & Central Asia',
                                                            'European Union',
                                                               'High income',
                         'Latin America & Caribbean (excluding high income)',
                                                                'Low income',
                                                       'Lower middle income',
                                                       'Low & middle income',
                         'Middle East, North Africa, Afghanistan & Pakistan',
                                                             'Middle income',
 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
                                                              'OECD members',
                                                                'South Asia',
                                'Sub-Saharan Africa (excluding high income)',
                                                        'Sub-Saharan Africa',
                                'East Asia & Pacific (IDA & IBRD countries)',
                              'Europe & Central Asia (IDA & IBRD countries)',
            'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
                                                   'South Asia (IDA & IBRD)',
                                 'Sub-Saharan Africa (IDA & IBRD countries)',
                                                       'Upper middle income',
                                                                     'World',
                                                              'South Africa']
Length: 30, dtype: str

In [7]:
years = df_physicians.columns[4:]
print("First year:", years[0])
print("Last year:", years[-1])
print("Total years:", len(years))

First year: 1960
Last year: Unnamed: 69
Total years: 66

In [8]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    missing_percent = df.isnull().mean() * 100
    print(missing_percent.sort_values(ascending=False).head())

PHYSICIANS
2024           100.000000
Unnamed: 69    100.000000
1963            93.984962
1962            93.984962
1964            93.984962
dtype: float64

GDP
Unnamed: 69    100.000000
1960            43.233083
1961            42.105263
1963            41.353383
1962            41.353383
dtype: float64

HEALTH_EXPENDITURE
1960    100.0
1961    100.0
1965    100.0
1964    100.0
1963    100.0
dtype: float64

POPULATION_GROWTH
1960           100.00000
Unnamed: 69    100.00000
1963             0.75188
1964             0.75188
1962             0.75188
dtype: float64

SCHOOL_ENROLLMENT
1960    100.0
1961    100.0
1965    100.0
1964    100.0
1963    100.0
dtype: float64

UNEMPLOYMENT
1960    100.0
1961    100.0
1965    100.0
1964    100.0
1963    100.0
dtype: float64

URBAN_POPULATION
Unnamed: 69    100.00000
1960             0.37594
1963             0.37594
1964             0.37594
1962             0.37594
dtype: float64

In [9]:
for name, df in datasets.items():
    print(name, df["Country Name"].nunique())

physicians 266
gdp 266
health_expenditure 266
population_growth 266
school_enrollment 266
unemployment 266
urban_population 266

In [10]:
df_physicians["2024"].isnull().mean() * 100

np.float64(100.0)

In [11]:
for year in ["2021", "2022", "2023", "2024"]:
    print(year, df_gdp[year].isnull().mean() * 100)

2021 3.007518796992481
2022 3.3834586466165413
2023 5.639097744360902
2024 9.774436090225564

In [12]:
years = ["2018", "2019", "2020", "2021", "2022", "2023", "2024"]

for y in years:
    if y in df_physicians.columns:
        valid = df_physicians[y].notnull().sum()
        total = df_physicians.shape[0]
        print(f"{y}: {valid} valid ({(valid/total)*100:.2f}%)")

2018: 157 valid (59.02%)
2019: 135 valid (50.75%)
2020: 136 valid (51.13%)
2021: 123 valid (46.24%)
2022: 172 valid (64.66%)
2023: 58 valid (21.80%)
2024: 0 valid (0.00%)